### ISSUE TITLE
JPEGmini not running

### ISSUE THREAD

**Issue by colmjude** [JamieMason/ImageOptim-CLI#109]
imageoptim-cli: 1.11.6
imageOptim: 1.5.4
JPEGmini: 1.8.7

When I run imageoptim I get the following error when it attempts to use JPEGmini
```execution error: System Events got an error: Can’t get sheet 1 of sheet 1 of window 1 of process "JPEGmini". Invalid index. (-1719)```

Any idea what is going wrong?

**Comment by paultreny** [comment]
It looks to me like the JPEGmini developers have disabled the the __File > Open…__ menu dropdown, which in turn disables the hotkey ( __⌘O__ ). This dropdown existed in past versions, but does not exist in any version of JPEGmini lite, normal or pro, I tested version 1.9.0. __imageoptim-cli__ relies on this hotkey existing when automating the image file selection process, and I imagine it will be difficult to script it to work (you'll have to move the mouse manually to the yellow __CHOOSE__ button)

![screenshot 2015-05-18 17 31 00](https://cloud.githubusercontent.com/assets/714208/7691120/01ce03ae-fd86-11e4-9cc3-7353854d2917.png)

I'd love to believe it's a bug, but I imagine it's more likely an intentional act by the JPEGmini developers, specifically designed to break the automation that imageoptim-cli offers, in a misguided attempt to drive users to their [JPEGmini Server](http://www.jpegmini.com/server) subscription service ($199/month). (If so, not cool dev, not cool... :-1:)

Drag and drop of an image file onto JPEGmini works, and clicking the yellow __CHOOSE__ button works, but the  (__⌘O__) hotkey support seems to be no more, at least unless the developer changes it back.

**Comment by cweekly** [comment]
Same issue -- but I think I've just resolved it!
OSX 10.9.5, node v0.12.3, npm 2.9.1, ImageOptim v1.5.6, imageoptim-cli 1.11.6.

Going through grunt (via grunt-imageoptim) was getting in the way of my debugging, so I have been using npm directly, eg 
  `find ./webapp.war/img -name '*.jpg' | imageoptim -j`

First: ImageOptim-CLI is a great tool. Thank you, Jamie Mason!
Now: Thank you so much, Paul "Serendipity*" Treny (*you posted this crucial info just SIX HOURS AGO... the Universe is smiling on me right now!).  
Confirmed: JPEGmini v1.9.0 disabled the File > Open menu, which may be responsible for breaking the current imageoptim-cli scripting mechanism.
Again per Paul, JPEGmini v1.8.7 doesn't have this issue, and he even provided this convenient DL link:
     http://mac.jpegmini.com/autoupdate/retail_v187/jpegmini_retail_89_update.app.zip

But, using 1.8.7, I *still* ran into the "can't get sheet 1 of window 1" problem.
I looked again at the console's system log (/Applications/Utilities/Console.app) to see what imageoptim was logging (after it had given up on jpegmini lossy pre-processing per its premature exit) ... and noticed tons of lines like
     "ImageOptim[15485]: Skipping /private/var/folders/..../imageoptim-cli/jpg/..... foo.jpg , because it has been optimized before."

Normally this is a sane / helpful aspect to ImageOptim. But in this case, because JPEGmini didn't get a chance to do its thing, the "already been chewed" heuristic is inappropriate. I totally get the concept of diminishing returns (and necessity of stopping in finite time, and trying to protect users from setting up dumb workflows) but when there's a real dependency on a 3rd party tool, accounting for breakage is necessary, to avoid this clippy-like "helpfulness". ;)

So this is a friendly / grateful vote in favor of supporting a "flush cache - yes I'm sure" kind of option in the api, IF you've got time / inclination to do so. If not, hopefully a quick note in the docs will help others? Or maybe they will find this issue's comment thread. In any case:  
JPEGmini makes a huge difference, and I am 100% sure I want imageoptim to forget about its past runs and simply start over. So, how to flush that cache? 

Googled "imageoptim how to flush cache", and the 3rd result was https://github.com/pornel/ImageOptim/issues/65 -- confirming others have wanted this cache flush option, and that it's not supported by the tool... so I kept looking in the console log, till I finally noticed this hiding in plain sight:
     "ImageOptim[15481]: Results cache is in /Users/cweekly/Library/Caches/ImageOptimResults.db"

So, I moved this file out of ~/Library/Caches and -- once more into the breach -- ran 
  `find ./webapp.war/img -name '*.jpg' | imageoptim -j`
... and ... it's working!! :)

Something like 27,000 images means it won't finish anytime soon... but it's working. Phew!
I hope this helps someone else.

**Comment by JamieMason** [comment]
Thanks ever so much. I'm on holiday but will pick up when I return home.

**Comment by paultreny** [comment]
The tip about flushing the cache is handy @cweekly , thanks! I hadn't run across that exact issue yet, but it's useful

Update on the JPEGmini __⌘O__ saga, I tweeted at them and they've said it's a bug, so hopefully it will be fixed in the next version.

https://twitter.com/paultreny/status/600422951746408448
>@jpegmini looks like the File > Open… menu & hotkey (⌘O) were intentionally disabled in 1.9.0? why? bug? Not cool! http://t.co/mIxekNwn8L

https://twitter.com/jpegmini/status/600568031165730816
> @paultreny Hi Paul - looks like you found a bug! No worries, we have our top developers working on it now.

**Comment by moramedia** [comment]
I hope it gets fixed soon... I'm doing it manually :(

**Comment by cweekly** [comment]
Right on, Jamie and Paul! :)
One more quick note about shell scripting imageoptim-cli for posterity (ie, for this tool's users): the sample command I noted for the success case will run into problems (ie "zsh: argument list too long: find") if it's run against too-large a set of files. So, instead of this:
` find ./webapp.war/img -name '*.jpg' | imageoptim -j `
you'll want to find a way to do it in passes, either by running the find redirect to a file and looping through that, or doing it in batches by limiting it to a given subdirectory depth via -depth or -mindepth and/or -maxdepth args:
` find . -name '*.jpg' -type f -maxdepth 3 | imageoptim -j`
(Checking the count via `... | wc -l` is a good idea too.)

Cheers! :)
Chris

**Comment by JamieMason** [comment]
Hey, are you saying Chris that the "can't get sheet" error is fixed by clearing imageoptim's cache? Also, the last comment about the find command, could you raise a separate issue for that please if it's unrelated? Will be easier for me to track. Thanks a lot Chris. 

Note to all: I'm currently on holiday and have 2 paid projects running at the same time when I return, it could be a few weeks before I can pick this up.

**Comment by cweekly** [comment]
Hi Jamie, 
Yes to first question, and N/A for 2nd. 

1) Yes, I was able to avoid the "can't get sheet" error with the following setup:
* OSX 10.9.3
* node 0.12.3
* npm@2.9.1
* imageoptim-cli@1.11.6
* ImageOptim.app v1.5.6
* JPEGmini v1.8.7 (not v1.9.0 which has a disabled "File > Open" menu item)

Steps after unsuccessful attempts with 1.9.0 and installing 1.8.7: 
 1. Clear the imageoptim cache: 'rm -rf ~/Library/Caches/ImageOptimResults.db`
 2. `find . -name '*.jpg' -type f -maxdepth 5 | imageoptim -j`

(At some point in here I may also have wiped OSX's ${TMPDIR} as well, ie `rm -rf ${TMPDIR}`, but IIRC that was not relevant to getting imageoptim-cli to trigger JPEGmini 1.8.7 via the -j arg.)

The find command's -maxdepth arg in this example relates to subdirectory traversal. I was dealing with deep directory structures and thousands of files, thus ran into shell limits (ie, `zsh: argument list too long: find`). For me, using -depth was the simplest solution to reduce the arg length. 

That also answers your 2nd question about the find command. It's not specific to imageoptim-cli at all, rather just something others might run into if they followed my initial example. 

Hope that helps! Have a great weekend!:)
C

**Comment by almone** [comment]
It looks like JPEGmini devs did their job and **⌘O** finally came back with 1.9.1.

**Comment by JamieMason** [comment]
Sorry for the delay, @almone @cweekly @moramedia @paultreny @colmjude — is this issue now fixed due to JPEGmini >=1.9.1?

**Comment by JamieMason** [comment]
imageoptim-cli@1.14.8 released, please reopen if this issue still stands.

**Comment by domainxh** [comment]
Just noticed my Jpegmini on macbook air stop running. I can't even get it to launch, after clicking on the icon, the icon jumps once but nothing happen afterwards. Any ideas?

**Comment by JamieMason** [comment]
@domainxh based on only what you've written there, that sounds like you have an issue with JPEGmini itself, I would contact the makers of that app. Thanks.
