### ISSUE TITLE
Bad data in optim vs alternative graph

### ISSUE THREAD

**Issue by scarstens** [JamieMason/ImageOptim-CLI#142]
I'm not sure how or where you got your data from, but I've used all these services and clearly I'm getting different results from the same image you posted you tested against:
![image](https://cloud.githubusercontent.com/assets/1483300/24730854/0df5a3fe-1a1b-11e7-9803-80ad760bac3d.png)
 TinyPNG clearly superior.

**Comment by JamieMason** [comment]
I'm not sure how or where you learnt discourse, but regardless I'll respond politely.

It's some time since i ran the comparison and over time each tool releases improvements, so the results can get out of date. Thanks for pointing this out, i will find some time to run them again and see where each tool stands.
